In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

print("Loading cleaned 2025 BIXI dataset...")
df = pd.read_csv('../data/processed/bixi_2025_cleaned.csv')

print(f"Successfully loaded {len(df):,} cleaned trip records.")
df.head()

Loading cleaned 2025 BIXI dataset...
Successfully loaded 13,990,411 cleaned trip records.

,STARTSTATIONNAME,STARTSTATIONARRONDISSEMENT,STARTSTATIONLATITUDE,STARTSTATIONLONGITUDE,ENDSTATIONNAME,ENDSTATIONARRONDISSEMENT,ENDSTATIONLATITUDE,ENDSTATIONLONGITUDE,STARTTIMEMS,ENDTIMEMS,duration_sec,start_date,end_date,start_hour,day_of_week,month,is_round_trip
0,St-Viateur / Casgrain,Le Plateau-Mont-Royal,45.53,-73.60,Parc Molson (d'Iberville / Beaubien),Rosemont - La Petite-Patrie,45.55,-73.59,1767118845159,1767119927367.00,1082.21,2025-12-30 18:20:45.159,2025-12-30 18:38:47.367,18,Tuesday,12,False
1,9e avenue / Masson,Rosemont - La Petite-Patrie,45.55,-73.57,Parc Molson (d'Iberville / Beaubien),Rosemont - La Petite-Patrie,45.55,-73.59,1767146967447,1767148054129.00,1086.68,2025-12-31 02:09:27.447,2025-12-31 02:27:34.129,2,Wednesday,12,False
2,St-Urbain / Laurier,Le Plateau-Mont-Royal,45.52,-73.59,Parc Molson (d'Iberville / Beaubien),Rosemont - La Petite-Patrie,45.55,-73.59,1766867149246,1766868275435.00,1126.19,2025-12-27 20:25:49.246,2025-12-27 20:44:35.435,20,Saturday,12,False
3,Parc de Turin (de Lanaudière / Jean-Talon),Villeray—Saint-Michel—Parc-Extension,45.55,-73.61,Parc Molson (d'Iberville / Beaubien),Rosemont - La Petite-Patrie,45.55,-73.59,1767227508567,1767228209866.00,701.30,2026-01-01 00:31:48.567,2026-01-01 00:43:29.866,0,Thursday,1,False
4,Parthenais / du Mont-Royal,Le Plateau-Mont-Royal,45.54,-73.57,Parc Molson (d'Iberville / Beaubien),Rosemont - La Petite-Patrie,45.55,-73.59,1766953764324,1766954798356.00,1034.03,2025-12-28 20:29:24.324,2025-12-28 20:46:38.356,20,Sunday,12,False

In [2]:
hourly_trips = df['start_hour'].value_counts().sort_index().reset_index()
hourly_trips.columns = ['hour', 'trip_count']

hourly_trips['pct_total'] = (hourly_trips['trip_count'] / len(df)) * 100

print("Trip Distribution by Hour of Day:")
display(hourly_trips)

Trip Distribution by Hour of Day:

    hour  trip_count  pct_total
0      0      772540       5.52
1      1      646704       4.62
2      2      527416       3.77
3      3      404285       2.89
4      4      265070       1.89
5      5      169443       1.21
6      6      108320       0.77
7      7       84657       0.61
8      8       46418       0.33
9      9       68053       0.49
10    10      168261       1.20
11    11      434460       3.11
12    12      768718       5.49
13    13      577117       4.13
14    14      528363       3.78
15    15      619964       4.43
16    16      743544       5.31
17    17      760495       5.44
18    18      775888       5.55
19    19      901246       6.44
20    20     1142004       8.16
21    21     1363268       9.74
22    22     1172615       8.38
23    23      941562       6.73